name: Compile Latex and Release PDF

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: LaTeX compile slides
        uses: xu-cheng/latex-action@v3
        with:
            root_file: |
                sci-img.tex
                sci-img-worksheet.tex
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
            files: |
              sci-img.pdf
              sci-img-worksheet.pdf
