name: Compile Latex and Release PDF

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Install TeXlive
        run: sudo apt-get update && sudo apt-get install texlive texlive-publishers texlive-science biber
      - name: LaTeX compile slides
        run: pdflatex sci-img; biber sci-img; pdflatex sci-img;pdflatex sci-img
      - name: LaTeX compile worksheet
        run: pdflatex sci-img-worksheet; biber sci-img-worksheet; pdflatex sci-img-worksheet; pdflatex sci-img-worksheet
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with: |
              sci-img.pdf
              sci-img-worksheet.pdf
